tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Render markdown on the CLI
brew "glow"
# Improved top (interactive process viewer)
brew "htop"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Enhanced version of john, a UNIX password cracker
brew "john-jumbo"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Mac App Store command-line interface
brew "mas"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Tiny, lightning fast, feature-packed file manager
brew "nnn"
# Platform built on V8 to build network applications
brew "node", link: false
# General-purpose scripting language
brew "php", restart_service: true
# Object-relational database system
brew "postgresql", restart_service: true
# Python version management
brew "pyenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"
# Terminal-based client for Spotify
brew "spotify-tui"
# Cross-shell prompt for astronauts
brew "starship"
# User interface to the TELNET protocol
brew "telnet"
# Terminal multiplexer
brew "tmux"
# Vi 'workalike' with many additional features
brew "vim", link: false
# Simple terminal image viewer written in Rust
brew "viu"
# Extensible IRC client
brew "weechat"
# Internet file retriever
brew "wget"
# Web browser focusing on privacy
cask "brave-browser"
# Web security testing toolkit
cask "burp-suite"
# Universal database tool and SQL client
cask "dbeaver-community"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Web browser
cask "firefox"
cask "font-fira-code"
# Free and open-source image editor
cask "gimp"
# Fork of Nylas Mail
cask "mailspring"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
cask "via"
# Open-source version of the X.Org X Window System
cask "xquartz"
