tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
# Command-line interface for SQLite
brew "sqlite"
# Record and share terminal sessions
brew "asciinema"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# Cross-platform make
brew "cmake"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Render markdown on the CLI
brew "glow"
# Improved top (interactive process viewer)
brew "htop"
# Command-line benchmarking tool
brew "hyperfine"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Enhanced version of john, a UNIX password cracker
brew "john-jumbo"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Rainbows and unicorns in your console!
brew "lolcat"
# Package manager for the Lua programming language
brew "luarocks"
# Mac App Store command-line interface
brew "mas"
# Fast, highly customisable system info script
brew "neofetch"
# Parser generator tool and incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Tiny, lightning fast, feature-packed file manager
brew "nnn"
# Platform built on V8 to build network applications
brew "node"
# Password manager
brew "pass"
# General-purpose scripting language
brew "php"
# Object-relational database system
brew "postgresql@14", restart_service: true
# Python version management
brew "pyenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"
# Terminal-based client for Spotify
brew "spotify-tui"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# User interface to the TELNET protocol
brew "telnet"
# Terminal multiplexer
brew "tmux"
# Vi 'workalike' with many additional features
brew "vim", link: false
# Simple terminal image viewer written in Rust
brew "viu"
# Extensible IRC client
brew "weechat"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# GPU-accelerated terminal emulator
cask "alacritty"
# 3D creation suite
cask "blender"
# Web browser focusing on privacy
cask "brave-browser"
# Web security testing toolkit
cask "burp-suite"
# Universal database tool and SQL client
cask "dbeaver-community"
# Web browser
cask "firefox"
# Free monospaced font with programming ligatures
cask "font-fira-code"
# Monospaced programming font inspired by the Minecraft typeface
cask "font-monocraft"
# Free and open-source image editor
cask "gimp"
# Vector graphics editor
cask "inkscape"
# Keyboard customizer
cask "karabiner-elements"
# Calculator and converter application
cask "numi"
# Open-source software for live streaming and screen recording
cask "obs"
# Administration and development platform for PostgreSQL
cask "pgadmin4"
# Collaboration platform for API development
cask "postman"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Keyboard configurator
cask "via"
# Open-source version of the X.Org X Window System
cask "xquartz"
