#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_border off
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
gap=8
padding=10
bottom_padding=$((gap+padding))
yabai -m config layout bsp
yabai -m config top_padding $padding
yabai -m config bottom_padding $bottom_padding
yabai -m config left_padding $padding
yabai -m config right_padding $padding
yabai -m config window_gap $gap

# settings for custom menu bar
yabai -m config external_bar all:40:0

# hide native macOS menu bar
#yabai -m config menubar_opacity 0.0

# create space if not exist and give label to it
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

# setup spaces
setup_space 1 code
setup_space 2 web
setup_space 3 music
setup_space 4 notes
setup_space 5 design
setup_space 6 mail
setup_space 7 other
setup_space 8 discord

# specific space settings
# yabai -m config --space 6 layout float

# bind apps to specific spaces
yabai -m rule --add app="Ghostty" space=code
yabai -m rule --add app="Arc" space=web
yabai -m rule --add app="Spotify" space=music
yabai -m rule --add app="Obsidian" space=notes
yabai -m rule --add app="Figma" space=design
yabai -m rule --add app="Mail" space=mail
yabai -m rule --add app="Fork" space=other

# link space to specific display
yabai -m space discord --display 2

# bind apps to extra displays
yabai -m rule --add app="Discord" space=8

# window rules
yabai -m rule --add app="^(System Settings|Preview|Books|Alfred|VIA|Activity Monitor|Installer|Telegram|Finder|Notes|Reminders|Mail|OBS|Numi)" manage=off

# apply rules to existing windows
yabai -m rule --apply

echo "yabai configuration loaded..."

# NOTE: add borders for active/inactive windows
# https://github.com/FelixKratz/JankyBorders
borders active_color=0xff51A098 inactive_color=0x00000000 width=8.0 &
