#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_border off
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
gap=10
yabai -m config layout bsp
yabai -m config top_padding $gap
yabai -m config bottom_padding $gap
yabai -m config left_padding $gap
yabai -m config right_padding $gap
yabai -m config window_gap 10

# specific space settings
# yabai -m config --space 6 layout float

# bind apps to specific spaces
yabai -m rule --add app="Alacritty" space=1
yabai -m rule --add app="Arc" space=2
yabai -m rule --add app="Spotify" space=3
yabai -m rule --add app="Obsidian" space=4
yabai -m rule --add app="Figma" space=5

# link space to specific display
yabai -m space 8 --display 2

# bind apps to extra displays
yabai -m rule --add app="Discord" space=8

# window rules
yabai -m rule --add app="^(System Settings|Books|Alfred|Activity Monitor|Installer|Telegram|Finder|Notes|Reminders|Mail|OBS|Numi)" manage=off

echo "yabai configuration loaded..."
